// Writes Shared/UI/Ember.xcassets/anchor.symbolset/anchor.svg from the same path the app
// draws. SF Symbols has no anchor, and an App Shortcut can only be handed a symbol *name* —
// no image, no view — so the one custom symbol in the project exists for Spotlight's tile.
// Generating it keeps that tile and the in-app mark the same drawing rather than two anchors
// that drift.
//
//   swiftc -parse-as-library -O scripts/make-anchor-symbol.swift Shared/UI/AnchorMark.swift -o /tmp/anchor-symbol \
//     && /tmp/anchor-symbol > Shared/UI/Ember.xcassets/anchor.symbolset/anchor.svg
//
// Re-run it whenever AnchorMark moves, then rebuild so the catalog recompiles.
import SwiftUI

@main
enum MakeAnchorSymbol {
    /// The nine weights the template asks for. The anchor is one drawing at every one of
    /// them: it is a mark, not a letter, and has no thin or bold cut.
    static let weights = ["Ultralight", "Thin", "Light", "Regular", "Medium", "Semibold", "Bold", "Heavy", "Black"]

    /// The template's three rows: the name, the baseline, the cap height between the guides,
    /// and how tall the anchor is drawn. The anchor stands above the cap line, sized so it
    /// lands beside `hourglass` and `tag.fill` in the Shortcuts row rather than under them.
    static let rows: [(name: String, baseline: Double, cap: Double, art: Double)] = [
        ("S", 696, 96, 126), ("M", 1276, 128, 168), ("L", 1856, 158, 207),
    ]

    static func main() {
        var symbols = "", guides = ""
        for row in rows {
            let width = AnchorMark.ink.width / AnchorMark.ink.height * row.art
            guides += line("Baseline-\(row.name)", x1: 200, y1: row.baseline, x2: 3200, y2: row.baseline)
            guides += line("Capline-\(row.name)", x1: 200, y1: row.baseline - row.cap, x2: 3200, y2: row.baseline - row.cap)
            for (index, weight) in weights.enumerated() {
                let x = 263 + Double(index) * 375
                let top = row.baseline - row.cap - 60, bottom = row.baseline + 60
                guides += line("left-margin-\(weight)-\(row.name)", x1: x, y1: top, x2: x, y2: bottom)
                guides += line("right-margin-\(weight)-\(row.name)", x1: x + width, y1: top, x2: x + width, y2: bottom)
                symbols += """
                  <g id="\(weight)-\(row.name)" transform="translate(\(f(x)) \(f(row.baseline)))">
                   <path d="\(path(height: row.art))"/>
                  </g>\n
                """
            }
        }
        print("""
        <?xml version="1.0" encoding="UTF-8"?>
        <svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="3300" height="2200" viewBox="0 0 3300 2200">
         <g id="Notes">
          <text x="120" y="140" font-size="44">Generated by scripts/make-anchor-symbol.swift from AnchorMark. Do not edit by hand.</text>
         </g>
         <g id="Guides" fill="none" stroke="#00AEEF" stroke-width="0.5">
        \(guides) </g>
         <g id="Symbols">
        \(symbols) </g>
        </svg>
        """)
    }

    static func f(_ v: Double) -> String { String(format: "%.2f", v) }

    static func line(_ id: String, x1: Double, y1: Double, x2: Double, y2: Double) -> String {
        "  <line id=\"\(id)\" x1=\"\(f(x1))\" y1=\"\(f(y1))\" x2=\"\(f(x2))\" y2=\"\(f(y2))\"/>\n"
    }

    /// The mark as SVG path data, `height` tall, its foot on the baseline and its left edge on x = 0.
    static func path(height: Double) -> String {
        let ink = AnchorMark.ink
        let scale = height / ink.height
        let placed = AnchorMark.outline.applying(
            CGAffineTransform(translationX: -ink.minX * scale, y: -ink.maxY * scale).scaledBy(x: scale, y: scale)
        )
        var d = ""
        placed.cgPath.applyWithBlock { element in
            let p = element.pointee.points
            switch element.pointee.type {
            case .moveToPoint: d += "M\(f(p[0].x)) \(f(p[0].y))"
            case .addLineToPoint: d += "L\(f(p[0].x)) \(f(p[0].y))"
            case .addQuadCurveToPoint: d += "Q\(f(p[0].x)) \(f(p[0].y)) \(f(p[1].x)) \(f(p[1].y))"
            case .addCurveToPoint: d += "C\(f(p[0].x)) \(f(p[0].y)) \(f(p[1].x)) \(f(p[1].y)) \(f(p[2].x)) \(f(p[2].y))"
            case .closeSubpath: d += "Z"
            @unknown default: break
            }
        }
        return d
    }
}
